### ISSUE TITLE
Can't use IAM role with aws s3, only users with key.

### ISSUE THREAD

**Issue by nirradi** [GrahamCampbell/Laravel-Flysystem#102]
Hi Graham, love this package, good work!

It is missing something - the option to not pass key/secret to the s3 config. This would work when you assign an IAM role to an EC2 instance for bucket permissions instead of using the key/secret of a user. This is the recommended approach when building applications over amazon ec2. 

Right now, inside the AwsS3Connector class, you throw an exception if key or secret are unset, but actually you should simply not add the "credentials" field to the auth object in this case. 

What do you think?

**Comment by wouterNL** [comment]
Could you release a new version with this update included?

**Comment by GrahamCampbell** [comment]
Yes. I will do soon. :)

**Comment by lmj0011** [comment]
>It is missing something - the option to not pass key/secret to the s3 config. This would work when you assign an IAM role to an EC2 instance for bucket permissions instead of using the key/secret of a user. This is the recommended approach when building applications over amazon ec2.

any update on this? I assume this will apply for the `~/.aws/credentials` file also

**Comment by Nizari** [comment]
Based on [S3 SDK Docs](https://docs.aws.amazon.com/aws-sdk-php/v3/guide/guide/credentials.html?highlight=memoize#memoizing-credentials).

This way it will search for a file location, then the environment variables and lastly the roles. You can also split these out.

**Comment by westonwatson** [comment]
The changelog suggests Ec2 Instance Profile Support was added back in;

## 3.0.3 - 2015-09-18

* Added support for configuring credentials with environmental variables, a ini
  file at `~/.aws/credentials`, or with Ec2 instance profiles instead of
  requiring their inclusion in the `aws.php` config file.

**Comment by GrahamCampbell** [comment]
We will never support those files, because there is a one to many driver relation, not at most one S3 connection, so that file makes no sense.
