### ISSUE TITLE
Need better explanation of some options in config/flysytem.php

### ISSUE THREAD

**Issue by lmj0011** [GrahamCampbell/Laravel-Flysystem#104]
https://github.com/GrahamCampbell/Laravel-Flysystem/blob/master/config/flysystem.php#L49-L56

Is there documentation about each of the different config options in the `config/flysytem.php`

for example the `awss3` connection:

-- 

`'pirate'   => false`

I'm not sure what that is to suppose to mean, possibly a typo? is meant to be `'private' ?`

--

`'scheme'          => 'https'`

What other schemes are valid here?

**Comment by MatthewBooth** [comment]
Also, how to add your own adapter and connector and use them. Currently not known and would really need this. This is very easy on the Symfony libraries for this. You simply create one, create the service and inject it.

**Comment by GrahamCampbell** [comment]
> I'm not sure what that is to suppose to mean, possibly a typo? is meant to be 'private' ?

Not actually a typo, it really does mean enable "pirate mode". This was something I added just for me, that turns off assertions, so I could reduce the number of requests to S3. This is a dangerous option however, so should be used with care.

> What other schemes are valid here?

Honestly, I have no idea off the top of my head. I can only recommend reading the source code to find out. I'd love some pull requests to improve the documentation. 👍 

> Also, how to add your own adapter and connector and use them. 

There are a few ways of doing this. The most basic method, would be to hijack the manager in the standard way of calling `extend()` as per the Laravel docs, however this will bypass all the factory objects in this package. There doesn't really exist a great way to do custom "connectors" right now. The best approach I guess would be to extend https://github.com/GrahamCampbell/Laravel-Flysystem/blob/master/src/Adapters/ConnectionFactory.php, and then rebind the new instance of that to the container. This will work great for apps, if you need something custom there, but will be crap for if you want to publish a package that adds a single adapter.
