### ISSUE TITLE
Laravel 5.6

### ISSUE THREAD

**Issue by fridzema** [GrahamCampbell/Laravel-Flysystem#107]
Hello,

Do you have plans to support laravel 5.6?

**Comment by w1n78** [comment]
this has been discussed at https://github.com/GrahamCampbell/Laravel-Flysystem/issues/106

the response is...

"In 2 weeks, I am upgrading all of my packages to only support 5.5 and 5.6 and PHP 7.1.3+. In the meanwhile I will not be accepting any PRs."
