### ISSUE TITLE
How to upload big video files in s3

### ISSUE THREAD

**Issue by kevin1193** [GrahamCampbell/Laravel-Flysystem#110]
Im planning to use this package in uploading videos in AWS S3, is there a way I can upload big file size ranging from 100MB to 500MB?

**Comment by martinbean** [comment]
@kevin1193 If it’s user-uploaded files, use the JavaScript SDK instead. It’ll handle the chunking, re-uploading failed parts etc.

https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/s3-example-photo-album.html
