### ISSUE TITLE
Laravel 5.8 support?

### ISSUE THREAD

**Issue by oriceon** [GrahamCampbell/Laravel-Flysystem#115]
Hi. I see you updated composer to support laravel 5.8. Can you relase new version please?

**Comment by GrahamCampbell** [comment]
I cannot tag a new release until the tests are updated. I'd accept a PR to do this. Otherwise, I'll get round to it eventually. Sorry I can't put a date on it.

**Comment by SudoGetBeer** [comment]
#116 should fix them

**Comment by SudoGetBeer** [comment]
@GrahamCampbell since the pull request is merged and all tests are are green, could you push a release if your time allows it?
Thanks

**Comment by GrahamCampbell** [comment]
I've released v5.2.0 with Laravel 5.8 support. Thanks for the PR @SudoGetBeer. I was making similar changes on my other packages a couple of weeks ago, but ran out of time to finish it off, so the PR was of great help. :)
