### ISSUE TITLE
[SECURITY] Need to Upgrade league/flysystem dependency to ^2.1.1

### ISSUE THREAD

**Issue by madhurbhaiya** [GrahamCampbell/Laravel-Flysystem#131]
There have been a security advisory for upstream library league/flystem

https://github.com/thephpleague/flysystem/security/advisories/GHSA-9f46-5r25-5wfm

However, when I try to update my composer.json, I am getting the following error

```
graham-campbell/flysystem[v7.1.0, ..., 7.1.x-dev] require league/flysystem ^1.1.1 -> found league/flysystem[1.1.1, ..., 1.x-dev] but it conflicts with your root composer.json require (^2.0)
```

Please issue a release upgrading the same

**Comment by GrahamCampbell** [comment]
On the 1.x series, it is sufficient to upgrade to 1.1.4 or higher. No need to jump to 2.x. Thanks for double checking though. :)
