### ISSUE TITLE
Can't require this package in L4

### ISSUE THREAD

**Issue by pdcmoreira** [GrahamCampbell/Laravel-Flysystem#26]
Hi,

In my L4 app's composer.json I'm trying to require this app like this:
"graham-campbell/flysystem": "~1.0"

But the composer says it can't, with the following message:

```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package graham-campbell/flysystem could not be found in any
version, there may be a typo in the package name.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your min
imum-stability setting
   see <https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion> f
or more details.

Read <http://getcomposer.org/doc/articles/troubleshooting.md> for further common
 problems.
```

Am I missing something?

**Comment by GrahamCampbell** [comment]
Yeh. You're going to need dev-stability to use 1.0 atm. It's not done yet. I'd actually recommend using "0.7.*@alpha" for now.

**Comment by pdcmoreira** [comment]
Oh, I'm so blind that I didn't see that there this issue was posted several times before.
You could leave one open, though, to prevent more people to do the same I did.

Really sorry and thanks for the quick response.
