### ISSUE TITLE
composer issue

### ISSUE THREAD

**Issue by davidstanley01** [GrahamCampbell/Laravel-Flysystem#27]
For branch 1.0, you have a requirement for Flysystem version 1.0.  Only problem, is Flysystem doesn't have a 1.0 branch.  Can you revert this back to require 0.5.*?

Thanks

**Comment by GrahamCampbell** [comment]
Please see the other 10 duplicate issues...

**Comment by davidstanley01** [comment]
Heh.  I guess I should've checked the other issues, first.  Sorry about that.  Thanks for the prompt and polite answer.
