### ISSUE TITLE
League\Flysystem\Adapter\AwsS3 not found

### ISSUE THREAD

**Issue by prapats** [GrahamCampbell/Laravel-Flysystem#29]
Hi,

As the `AwsS3` adapter (and others) has been moved to its own repo on their latest version in the `thephpleague/flysystem`, it causes errors on `AwsS3Connector`, and I think all other connectors as well. 

Is there any workaround I can fix this?

Cheers

**Comment by GrahamCampbell** [comment]
Yeh. Use my latest tagged release for now. I'm going to update the 1.0 and master branches at the weekend to work with recent changes to the upcoming flysystem 1.0 release.

**Comment by prapats** [comment]
Thanks mate

**Comment by GrahamCampbell** [comment]
@prapats Hi there! I decided to do this right now. Check out https://github.com/GrahamCampbell/Laravel-Flysystem/commit/56c495e60fc7f9a728f57c48b322f68b637cd9a1. :)

**Comment by prapats** [comment]
Cheers @GrahamCampbell, I will try this out soon :D
