### ISSUE TITLE
Publishing configuration

### ISSUE THREAD

**Issue by jasonvarga** [GrahamCampbell/Laravel-Flysystem#40]
I'm trying to install your package and am running into an issue. I haven't worked with orchestral before, so I might be missing something obvious.

I've followed the steps in the readme - added `"graham-campbell/flysystem": "~2.0"` and a flysystem dependency to composer.json; added the service provider and facade. 

Running `php artisan publish:config graham-campbell/flysystem` like you suggest gives me a `exception 'InvalidArgumentException' with message 'There are no commands defined in the "publish" namespace.'` error.

I suspect I'm missing something to do with orchestral, but I don't know what.

Any help would be appreciated. Thanks.

**Comment by GrahamCampbell** [comment]
You haven't followed the install instructions for orchestral's config component. Also, I'll be ripping out and redoing the config system very soon.

**Comment by jasonvarga** [comment]
Looks like `publish:config` has been removed from Laravel.
https://github.com/laravel/framework/commit/0561d92c4b9e2ee7ef3e5b80d2ed1b5b83d4ed65

**Comment by GrahamCampbell** [comment]
Yeh, I know. I'm not suggesting you use it?

**Comment by jasonvarga** [comment]
I must be missing something then. Where do we put our configuration?

**Comment by GrahamCampbell** [comment]
My readme details it. As I said, I'm about to rewrite this. So, the current system will change today or tomorrow.

**Comment by GrahamCampbell** [comment]
I've made the changes. See the new instructions: https://github.com/GrahamCampbell/Laravel-Flysystem#configuration.

**Comment by jasonvarga** [comment]
Works great, thanks!
