### ISSUE TITLE
Override config from within code

### ISSUE THREAD

**Issue by jasonvarga** [GrahamCampbell/Laravel-Flysystem#43]
Hi Graham,

Is there a way to override the config on the fly?

For instance, I want to browse the authenticated user's filesystem using their token from the database, not mine.

`Flysystem::read('foo.txt')` works fine if I hardcode the token into `flysystem.php`.

**Comment by jasonvarga** [comment]
I added this to your `FlysystemManager` class.

``` php
public function setConnectionConfig($value, $name = null)
{
  $name = $name ?: $this->getDefaultConnection();

  $this->config->set($this->getConfigName().'.connections.'.$name, $value);
}
```

Then I was able to do this in my code:

``` php
$config = $flysystem->getConnectionConfig();

$config['token'] = $token;

$flysystem->setConnectionConfig($config);
```

It works, but I don't know if this would be considered a good solution.
If you'd like, I can open a PR, or if not I'd love to hear an alternative.

**Comment by GrahamCampbell** [comment]
> Is there a way to override the config on the fly?

Yes, just use set the config using the config facade or something similar. We're injecting the entire config repository, so we're always reading the latest config rather than having it read an injected once at the start.

**Comment by jasonvarga** [comment]
Oh, ha. Much easier. Thanks, works perfectly.

**Comment by GrahamCampbell** [comment]
No problem. Any other question or suggestions, you know where I am. :)
