### ISSUE TITLE
Flysystem sftp

### ISSUE THREAD

**Issue by danr1979** [GrahamCampbell/Laravel-Flysystem#45]
Hi. 

I am having difficulty getting the flysystem sftp plugin to work. Would you be able to provide an example of how to use it to upload a file please? Should I use the "upload" method or perhaps "copy"? I've used the regular flysystem adapter OK but I constantly get a "file not found" message when using the sftp adapter even though the file exists. 

The only thing I've noticed from the stack trace is that the path to the file has the leading slash stripped off by the flysystem library which invalidates the path. 

I'd appreciate any help you can offer. 

Thanks.

**Comment by GrahamCampbell** [comment]
The api is identical to all other drivers. If you're experiencing issues, take it up with flysystem itself. My code doesn't deal with that stuff. :)

**Comment by GrahamCampbell** [comment]
See the examples in my readme. It's possible you're using the methods wrong.

**Comment by danr1979** [comment]
OK thanks.
