### ISSUE TITLE
writeStream() closes resource?

### ISSUE THREAD

**Issue by nextpulse** [GrahamCampbell/Laravel-Flysystem#46]
I am using S3 (Laravel 5):

$stream = fopen($filename, 'r');
Flysystem::writeStream($filename, $stream);
fclose($stream);	

Everything works fine (file is correctly upload to S3), except:

fclose() always gives the error '... not a valid stream resource'

Any clues?

**Comment by GrahamCampbell** [comment]
I suspect that's because flysystem closes it for you.

**Comment by GrahamCampbell** [comment]
You you can just do this: `Flysystem::writeStream($filename, fopen($filename, 'r'));`
