### ISSUE TITLE
Any plans to integrate with Google Drive?

### ISSUE THREAD

**Issue by marlongichie** [GrahamCampbell/Laravel-Flysystem#47]
This is a great package by @GrahamCampbell . 

Google Drive is quite a prominent storage option for lots of users. Would be great to have an adapter for that integration as well.

Any thoughts?

**Comment by GrahamCampbell** [comment]
If a flysystem google drive adapter appears on https://github.com/thephpleague, then I'll add a "connector" for it here, sure. No such adapter currently exists though, sorry.
