### ISSUE TITLE
Cache-control (and other) metadata for Amazon S3

### ISSUE THREAD

**Issue by bipinu** [GrahamCampbell/Laravel-Flysystem#49]
It would be nice to update file metadata so that it serves appropriate cache headers.
I followed this guideline: https://github.com/thephpleague/flysystem/issues/141#issuecomment-42827420
However, the following code doesn't seem to have any impact:
```
$this->flysystem->write($destLocation, $file, ['Cache-Control' => 'max-age=3153600, public']);
```
Am I missing something?

**Comment by GrahamCampbell** [comment]
D'no, but this is unrelated to my wrapper. Sorry I can't be any help.

**Comment by bipinu** [comment]
Is there a way to pass metadata/options using your wrapper?

**Comment by GrahamCampbell** [comment]
Yes. In exactly the same way. We're just forwarding function calls dynamically.

**Comment by danmichaelo** [comment]
For others who google this and end up here: The fix is to change 'Cache-Control' to 'CacheControl', per https://github.com/thephpleague/flysystem-aws-s3-v2/blob/master/src/AwsS3Adapter.php#L32
