### ISSUE TITLE
Local.php $this->getPathPrefix() not being set properly

### ISSUE THREAD

**Issue by pfeiferchristopher** [GrahamCampbell/Laravel-Flysystem#50]
So I'm having a strange issue. I'm attempting to use `$flysystem->connection('local')->getSize('videos/video.mp4');` but I'm receiving the following error.
```php
RuntimeException in Local.php line 339:
SplFileInfo::getType(): Lstat failed for /home/vagrant/code/user/public/videos/video.mp4
```
And as you can see it is looking with `/home/vagrant/code/user/public` but my public directory is `public_html/` which I have set with Flysystem's config
```php
'local' => [
    'driver'     => 'local',
    'path'       => public_path(),
    // 'visibility' => 'public',
    // 'eventable'  => true,
    // 'cache'      => 'foo'
],
```
And I've tested with `php artisan tinker` that `public_path()` does in fact return `/home/vagrant/code/user/public_html/` and I can not figure it out. I went ahead in debugging this issue within the constructor on `Local.php` set `$this->setPathPrefix('/home/vagrant/code/user/public_html/');` and everything worked. So that is how I know it is that the root directory path is not being set.

Any help would be much appreciated.

**Comment by GrahamCampbell** [comment]
I can't replicate this not working.

**Comment by GrahamCampbell** [comment]
Anyone?

**Comment by pfeiferchristopher** [comment]
I haven't used the local driver since I opened this issue so I can't say it's still an issue but for now I'll close this.

**Comment by popalin** [comment]
I had the same error. The path was wrong.
