### ISSUE TITLE
AWSS3 0 byte downloads

### ISSUE THREAD

**Issue by sergeh** [GrahamCampbell/Laravel-Flysystem#62]
I'm not exactly sure what I'm doing wrong but for some reason when I try to force a download it returns a 0 byte file even though the file is in the bucket. Uploading files to the bucket works fine.

Here's what I have for forcing a download via ajax when a user clicks a button

      $exists = Flysystem::has($file_path);

      if ($exists) {
        $stream = Flysystem::readStream($file_path);
        return Response::stream(function() use($stream) {
            fpassthru($stream);
        }, 200, [
            'Content-Type' => Flysystem::getMimetype($file_path),
            "Content-Length: " => Flysystem::getSize($file_path),
            "Content-disposition" => "attachment; filename=\"" . basename($file_path) . "\"",
        ]);
      }

`getSize` and `getMimetype` return the correct info but `stream_get_contents($stream)` returns null, any ideas why?

**Comment by GrahamCampbell** [comment]
Please ask the maintainers of flysystem.
