### ISSUE TITLE
Ability to add custom configuration properties?

### ISSUE THREAD

**Issue by igorsantos07** [GrahamCampbell/Laravel-Flysystem#69]
I've noticed Flysystem enables us to add custom `$config` items to our filesystem instances... However, when Laravel instanciates them from the `config/filesystem.php` it stripes down any unknown properties.

I was wondering if there's any special reason for that?
I'm using local filesystem for development but S3 for production, and would like to set different base URLs for each driver inside their configuration properties, and I think it would be great if this was possible inside the disk configuration itself.

**Comment by igorsantos07** [comment]
Hm... or should this be reported directly in the framework repository?

**Comment by GrahamCampbell** [comment]
> Hm... or should this be reported directly in the framework repository?

This package is not official to laravel, and is not needed to use laravel's basic storage stuff. This package is simply here to provide proper and total integration with flysystem.

**Comment by GrahamCampbell** [comment]
> I've noticed Flysystem enables us to add custom $config items to our filesystem instances... However, when Laravel instanciates them from the config/filesystem.php it stripes down any unknown properties.

What config options are missing?

**Comment by igorsantos07** [comment]
I tried to add a custom one, so I could use it along with the driver, but
the current code uses `Arr::only()` to ensure only known configuration
properties pass through. That precisely forbids us to use the config
feature from Flysystem.

Suggestions:

- simply remove the `only()` call. This would allow for credentials and
whatnot be accessible easily, what could be a security breach?
- use a blacklist approach instead of whitelist, cleaning up credentials
and allowing other properties to pass through. This is similar to the
current implementation, and would only change the `Arr` method used and
properties verified.
- pass as second argument to the Flysystem constructor a nested "config"
array, if there's a "config" key inside the driver parameters. This would
turn this ability to add custom config more explicit.

I'm happy to PR this if we agree with a solution :)

Igor Santos
[sent from my phone]

**Comment by GrahamCampbell** [comment]
I don't intend to change the whitelist system unless there is good reason to.

Please could you tell me what use case youactually have for changing it.

**Comment by igorsantos07** [comment]
I just found the "offending" line, it's actually in [`Illuminate\Filesystem\FilesystemManager`](https://github.com/laravel/framework/blob/5.2/src/Illuminate/Filesystem/FilesystemManager.php#L242).

My idea is as follows:
In `config/filesystem.php` I have the default as `(getenv('APP_ENV') == 'prod')? 's3' : 'local'`. Given that, in my local machine I would need the file URLs relative to the server URL (path = '/'), and in production, relative to my bucket URL (path = 'https://aws.com/xyz/bucket/'). I would then, use something like `Storage::drive()->getConfig()->get('path') + $user->avatar_path` to spit out the user profile picture.

I was able to test this idea by simply commenting out the said line 242 in FilesystemManager.php.

**Comment by GrahamCampbell** [comment]
> I just found the "offending" line, it's actually in Illuminate\Filesystem\FilesystemManager.

That's got nothing to do with this package.

**Comment by igorsantos07** [comment]
Yeah, I noticed that when I was searching the source here. I'm going to report the issue there.
I though this was a subtree of Laravel, but what's actually this package? It seems its features are already part of the framework itself...

**Comment by GrahamCampbell** [comment]
> It seems its features are already part of the framework itself...

This package came first then the framework added something similar, but the one included in laravel's core doesn't support anywhere near the amount of features that this package supports. For example, you are very limited to what drivers you use in laravel/framework's implementation, and caching is not available to you.

**Comment by igorsantos07** [comment]
Uhhhhh. Indeed, I saw information on caching in Flysystem but not in Laravel docs. Gotta note this package in my issues for later reference, if I need it. Thanks for the support, man :)

**Comment by GrahamCampbell** [comment]
No worries. ;)
