### ISSUE TITLE
Google Cloud Support

### ISSUE THREAD

**Issue by devthiagolino** [GrahamCampbell/Laravel-Flysystem#73]
The package supports the google cloud storage?

**Comment by GrahamCampbell** [comment]
No. There is no flysystem package for it as far as I know. If there is an official one, then I will support it.

**Comment by stemsmit** [comment]
It appears a package has been developed by another party(Linked below), do you only provide support for packages developed by thephpleague?

https://github.com/Superbalist/flysystem-google-cloud-storage
