### ISSUE TITLE
Images can't be readed.

### ISSUE THREAD

**Issue by Advil-Robin** [GrahamCampbell/Laravel-Flysystem#74]
Hi,

I'm currently having a MAJOR issue...

I want to be able to store files on my storage server of 1TB, wich is extern from my other production server. I want to be able to upload and read images. How should I upload them? And how should I be able to read them? Since now I'm using this code to read them:

`GrahamCampbell\Flysystem\Facades\Flysystem::read('logo_small.png')`

But, that doesn't work that well.... It outputs something like this: 

`�PNG  IHDR���˱�	pHYs�� 5iCCPPhotoshop ICC profilexڵ�WTS���9'���Ρ7C/DJhE���%`H"*8��H����8�X"�mP��	2(���� ����νkݧ;����o�o����~�2�rYd�?����z�	f`$�d�����=���������MtK���?/��`����H�#@`iR\|�줨Hr��e�DT%lH��O��;凛E��V�L� ��̒ҳ��c��Me/[�CV.��#W!�F`}�<[@��0[&���0U ����S����`��ss�ps�8q���0� 2�"��+.>������]*d�S�4P6��!��p�	��|!B!� �R!d������v����M�G�N�Y�W�:܂��axc�&!#L��� F�9b�8!\d&��B"�x$IA��)@�"�H9R��#Mȯ�	�,r	�G�!��(���b(e��j�rQ?4�B�)�tZ�nF���چ�E���P%���cZ�1������dL���J�J�k�:�^���^b�$��8/B!� $,!�$l"��=��A���I�'�=�|b1��G,&V���o���I$�ɒ�N !œ�H�I�H;I��.R?i�4N&�uȶdorY@������C�3��0�#�N1�8Q�(	)��RI9H9M�<�LPը�TOjUD]J-�6R;�ר��	�:͒�M�����Ъh-�󴇴�t:݄�A�K��Wӫ������O � ��X�P063�3��o�L�ӗ���373��瘏�UX*v*|��*�Z�6��W�TUsU?�E��T+U��^S}�FU�P��	�V�ժ�P��6��RwT�P�Tߤ~P����Y�B#PC�Q��W���c��x,!k-��u�5�&�-�|v�����=��������Y�yJS��iYh��2�ʴ�h���<�`��4����Z� L������-�.�nվ��Y�	�I�٪Ӯ�H��k�;W7Ow��yݗzl=/=�^��������~��r���W��  � � � ��4�2�5L3�0�G��O�̈�hͤd&f��jHӥ=Y�Y�Y�ٶ����%�K�/����� 9s:�ly����J�N1�;3�6�c^L��|�|i�ե6K7.}�,h���	˅˻����[Q�Y���{�骢Uë�WXC[����B����wkc�v�.Z���X�XV|g����$�6:o����DTr�ԡ����&���?`

And that's not what it must display, itneeds to show an image. How?

**Comment by GrahamCampbell** [comment]
This doesn't appear to be related to my bridge, sorry.

**Comment by GrahamCampbell** [comment]
That output looks correct?

**Comment by Advil-Robin** [comment]
Well it displays my image (.jpg) as text, it needs to be displayed as an image...

**Comment by GrahamCampbell** [comment]
That's because you're not telling the browser the correct content type.

**Comment by Advil-Robin** [comment]
Ohw totally forget that. Thanks

**Comment by Advil-Robin** [comment]
Maybe not the place to ask the question, but can you read the filenames inside a folder? And show all these names in an array or so? (Using webdav plugin).
