### ISSUE TITLE
Azure Connector error

### ISSUE THREAD

**Issue by lapswr** [GrahamCampbell/Laravel-Flysystem#77]
Error 
`Argument 1 passed to GrahamCampbell\Flysystem\Adapters\AzureConnector::getAdapter() must be an instance of WindowsAzure\Blob\Internal\IBlob, instance of MicrosoftAzure\Storage\Blob\BlobRestProxy given, called in /var/www/laravelproject/vendor/graham-campbell/flysystem/src/Adapters/AzureConnector.php on line 42 and defined`

After the update to Azure library,
the azure connector has wrong namespaces
so the instead of this
`use WindowsAzure\Blob\Internal\IBlob;`
`use WindowsAzure\Common\ServicesBuilder;`

uses should be
`use MicrosoftAzure\Storage\Blob\Internal\IBlob;`
`use MicrosoftAzure\Storage\Common\ServicesBuilder;`

@GrahamCampbell  please can you confirm?

**Comment by GrahamCampbell** [comment]
Hmmm. Was this a recent breaking change they made?

**Comment by lapswr** [comment]
Yeah i think from may related issue in flysystem at thephpleague
https://github.com/thephpleague/flysystem/issues/647

**Comment by GrahamCampbell** [comment]
Thanks for the information. :)
