### ISSUE TITLE
S3 Credentials Configuration

### ISSUE THREAD

**Issue by lukewaite** [GrahamCampbell/Laravel-Flysystem#78]
Would you be open to a PR which allows the user to directly set `credentials` on the s3 configuration?

https://github.com/GrahamCampbell/Laravel-Flysystem/blob/master/src/Adapters/AwsS3Connector.php#L69

This would allow a user to pass in a [`CredentialProvider`](http://docs.aws.amazon.com/aws-sdk-php/v3/guide/guide/credentials.html#credential-provider). 

My use case is to pass in something implementing [`CacheInterface`](http://docs.aws.amazon.com/aws-sdk-php/v3/api/class-Aws.CacheInterface.html) to avoid hitting the aws metadata api on every request as we deploy credentials via IAM roles.

**Comment by GrahamCampbell** [comment]
You can do this by using the factory class provided rather than the manager.

**Comment by GrahamCampbell** [comment]
Something like this:

```php
use GrahamCampbell\Flysystem\Adapters\ConnectionFactory;
use League\Flysystem\Filesystem;

$config = [...];

$adapter = app(ConnectionFactory::class)->make($config);

$flysystem = new Filesystem($adapter);
```

**Comment by GrahamCampbell** [comment]
> This would allow a user to pass in a CredentialProvider.

Ah, right. I see what you mean. Yes, I'd accept a PR for that. :)
