### ISSUE TITLE
Can't get access to the "Disks" I have created

### ISSUE THREAD

**Issue by paulatwilson** [GrahamCampbell/Laravel-Flysystem#79]
Hiya mate, 

I have been wracking my brain and I know i am doing something very stupid. 

I have added some “Drives” in the Filesystem.php file but I don’t know how to get access to them Any help would be great.

I tried: 
``
Flysystem::connection('contract-processor')->read('document-list.json');
``

But that is obviously wrong as it tells me ‘contract-processor’ is not configured.

```
'disks' => [
    'local' => [
        'driver' => 'local',
        'root' => storage_path('app'),
    ],
    'public' => [
        'driver' => 'local',
        'root' => storage_path('app/public'),
        'visibility' => 'public',
    ],
    's3' => [
        'driver' => 's3',
        'key' => ‘key stuff',
        'secret' => ’stuff',
        'region' => 'eu-west-1',
        'bucket' => ‘bucket stuff',
    ],
  'contract-processor' => [
    'driver' => 'local',
    'root' => storage_path('contract-processor'),
  ]
],
```

**Comment by GrahamCampbell** [comment]
This package doesn't have anything to do with laravel's flysystem stuff. No concept of disks here.

**Comment by GrahamCampbell** [comment]
You need to add connections in your published version of:

https://github.com/GrahamCampbell/Laravel-Flysystem/blob/master/config/flysystem.php
