### ISSUE TITLE
Upload Image 

### ISSUE THREAD

**Issue by 3a6ala** [GrahamCampbell/Laravel-Flysystem#80]
Thanks for this Awesome API , in fact i can upload files , but i need your help to upload images 

i try to use put() method but do not work with me

**Comment by lmj0011** [comment]
@GrahamCampbell 

So can you upload images or not? If so, how is that achieved?

**Comment by lmj0011** [comment]
>So can you upload images or not? If so, how is that achieved?

got my answer here:
streams: http://flysystem.thephpleague.com/api/#using-streams-for-reads-and-writes
