### ISSUE TITLE
AWS Credentials are mandatory in the configuration file

### ISSUE THREAD

**Issue by emigm** [GrahamCampbell/Laravel-Flysystem#82]
It seems that the AWS [guidelines](http://docs.aws.amazon.com/aws-sdk-php/v2/guide/credentials.html#credential-profiles) are not followed entirely due to the credentials are mandatory in the configuration file.

That being said, the [#81](https://github.com/GrahamCampbell/Laravel-Flysystem/pull/81) removes that restriction.

**Comment by GrahamCampbell** [comment]
See my comment on the PR for my reasoning here. :)

**Comment by emigm** [comment]
I totally disagree with you due to this fix only gives to the developer another way to configure the AWS credentials making the implementation compliant with the AWS guidelines.
Also, it allows the developer to forget about the credentials and let the operation team to worry about them.
Finally, it also encourage good practices in terms of security due to the credentials are not committed in the repository.
