### ISSUE TITLE
Google Drive Support?

### ISSUE THREAD

**Issue by whfamily2006** [GrahamCampbell/Laravel-Flysystem#84]
this package not supported google drive now?

**Comment by GrahamCampbell** [comment]
I'm not aware of a league drive adapter. Once/if there is one, I will support it here.

**Comment by tomhatzer** [comment]
leage doesn't have a drive adapter, but there's one outside of league: 

Google Drive: https://github.com/nao-pon/flysystem-google-drive
Google Cloud Storage: https://github.com/Superbalist/flysystem-google-cloud-storage

**Comment by GrahamCampbell** [comment]
If those two authors could collaborate, and get one package into the league, then I will support it. :)
