### ISSUE TITLE
Very, Very weird behavior

### ISSUE THREAD

**Issue by tjvanderende** [GrahamCampbell/Laravel-Flysystem#85]
Hello,

Whenever I try to add the provider to my provider array and try afterwards to run my laravel website with php artisan serve (Or any command with artisan...) I get this errors in the command line tool:
VirtualAlloc() failed: [0x00000008],
VirtualFree() failed: [0x000001e7],
PHP Fatal error:  Out of memory (allocated 1816133632) (tried to allocate 262144 bytes)

Can't find anyone else with these problems, so pleeease help... I'm kinda desperate at this moment.

(NOTE: The same code I use now in my Laravel project, did work in a Lumen installation.........).

**Comment by GrahamCampbell** [comment]
Looks like a bug in PHP, or an infinite loop in your code. Xdebug will be useful to find infinite loops, since it has a recursive call limit.
