### ISSUE TITLE
Any redundancy with Laravel 5.4 filesystem? Any advise on flysystem-sftp integration?

### ISSUE THREAD

**Issue by volei** [GrahamCampbell/Laravel-Flysystem#89]
Sorry, is this the right place to ask?

I couldn't find out anything on whether this package is already integrated in Laravel 5.4, or what would be the additional benefit.
If already integrated: any advise on how to manually or maybe even composer integrate flysystem-sftp, or would that conflict?

I am asking because I don't want to mess up anything.

Rgds

**Comment by GrahamCampbell** [comment]
Please read the installation section of the readme. It specifically mentions that package.

**Comment by GrahamCampbell** [comment]
> I couldn't find out anything on whether this package is already integrated in Laravel 5.4, or what would be the additional benefit.

With regards to that question, this is totally separate from the laravel core implementation, and was created first. This package supports many more drivers, and also supports various other things such as caching.

**Comment by volei** [comment]
Thanks a lot, it looks like all worked fine. I integrated GrahamCampbell/Laravel-Flysystem and thephpleague/flysystem-sftp into my existing 5.4 project and did some use tests. Great tool!
