### ISSUE TITLE
examples of how to set other connections/adapters

### ISSUE THREAD

**Issue by lmj0011** [GrahamCampbell/Laravel-Flysystem#90]
I have no clue on how to config this package to work with AWS S3, from reading the README. Where's the examples on configuring each of the cloud providers?

after checking out this package https://github.com/thephpleague/flysystem-aws-s3-v3, which give the example I'm looking for, it doesn't seem that I need Laravel-Flysystem at all.

**Comment by GrahamCampbell** [comment]
Examples are given at https://github.com/GrahamCampbell/Laravel-Flysystem/blob/master/config/flysystem.php#L40.

**Comment by lmj0011** [comment]
I suppose I may have stumbled to that file after a few hours.

**Comment by lmj0011** [comment]
I see it said here now: https://github.com/GrahamCampbell/Laravel-Flysystem#flysystem-connections

about to submit a PR
