### ISSUE TITLE
Composer returning old version?

### ISSUE THREAD

**Issue by PunchRockgroin** [GrahamCampbell/Laravel-Flysystem#95]
A heads up but when installing for Laravel 5.4 and calling composer require graham-campbell/flysystem it seems to pull an old version. Mostly I'm looking for the new Dropbox v2 adapter so when I use the connection it errors out with "Class 'Dropbox\Client' not found"

I cleared my composer cache and ensured that I have ^3.7 in my local composer.json, so I don't think it's an issue here locally. As well, during install, I can also see after composer finishes the code in vendor doesn't reference "srmklive/flysystem-dropbox-v2" anywhere.

Thanks!

**Comment by PunchRockgroin** [comment]
Nevermind. I mistakenly thought that the latest version tagged had the master files. My bad.

**Comment by GrahamCampbell** [comment]
Will release soon. Just gotta test a few more things.
